# fly.toml app configuration file generated for remix-jokes-pj on 2023-06-10T00:47:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-jokes-pj"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
